import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(__dirname, '..', 'index.html'), 'utf8');
const js = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]).sort((a, b) => b.length - a.length)[0];
eval(js.replace("if(typeof module !== 'undefined') module.exports =", 'globalThis.__t ='));
const { pascal, goType, jsonToGo } = globalThis.__t;

let n = 0;
const check = (name, fn) => { fn(); n++; console.log('  ok -', name); };

check('pascal-cases keys, dropping separators', () => {
  assert.equal(pascal('name'), 'Name');
  assert.equal(pascal('first_name'), 'FirstName');
  assert.equal(pascal('user-id'), 'UserId');
  assert.equal(pascal('created at'), 'CreatedAt');
});

check('scalar Go types', () => {
  assert.equal(goType('x', 0), 'string');
  assert.equal(goType(true, 0), 'bool');
  assert.equal(goType(42, 0), 'int');
  assert.equal(goType(3.14, 0), 'float64');
  assert.equal(goType(null, 0), 'interface{}');
});

check('array types infer from the first element', () => {
  assert.equal(goType(['a', 'b'], 0), '[]string');
  assert.equal(goType([1, 2], 0), '[]int');
  assert.equal(goType([], 0), '[]interface{}');
});

check('simple struct with json tags', () => {
  const go = jsonToGo('{"name":"Ada","age":36}', 'User');
  assert.equal(go, 'type User struct {\n\tName string `json:"name"`\n\tAge int `json:"age"`\n}');
});

check('float and bool fields', () => {
  const go = jsonToGo('{"pi":3.14,"ok":false}', 'M');
  assert.ok(go.includes('Pi float64 `json:"pi"`'));
  assert.ok(go.includes('Ok bool `json:"ok"`'));
});

check('array field', () => {
  const go = jsonToGo('{"tags":["a","b"]}', 'M');
  assert.ok(go.includes('Tags []string `json:"tags"`'));
});

check('nested object becomes a nested struct', () => {
  const go = jsonToGo('{"address":{"city":"London"}}', 'M');
  assert.ok(go.includes('Address struct {'));
  assert.ok(go.includes('City string `json:"city"`'));
});

check('snake_case key keeps original in the json tag', () => {
  const go = jsonToGo('{"first_name":"x"}', 'M');
  assert.ok(go.includes('FirstName string `json:"first_name"`'));
});

check('root name is pascal-cased and defaults', () => {
  assert.ok(jsonToGo('{}', 'my_type').startsWith('type MyType struct'));
  assert.ok(jsonToGo('{}').startsWith('type AutoGenerated struct'));
});

check('invalid JSON throws', () => {
  assert.throws(() => jsonToGo('{not json}', 'M'), /invalid JSON/);
});

console.log(`\n${n} checks passed.`);
